#!/usr/bin/env python3
"""Seed 100 sample books for a tenant identified by the admin's email address.

Usage:
    python seed_books.py <admin_email>

Example:
    python seed_books.py admin@mybookstore.com
"""

import subprocess
import sys


def get_tenant_id(email: str) -> str:
    """Look up tenant_id for the given admin email via psql inside the postgres container."""
    query = f"SELECT tenant_id FROM users WHERE email = '{email}' LIMIT 1;"
    result = subprocess.run(
        [
            "docker",
            "compose",
            "exec",
            "-T",
            "-e",
            "PGPASSWORD=changeme_strong_password_here",
            "postgres",
            "psql",
            "-U",
            "bookstore",
            "-d",
            "bookstore",
            "-t",
            "-A",
            "-c",
            query,
        ],
        capture_output=True,
        text=True,
        cwd="/root/docs/projects/book-store-app/app",
    )
    tenant_id = result.stdout.strip()
    if not tenant_id:
        print(f"ERROR: No user found with email '{email}', or that user has no tenant.")
        print(f"psql stderr: {result.stderr.strip()}")
        sys.exit(1)
    return tenant_id


def main():
    if len(sys.argv) < 2:
        print("Usage: python seed_books.py <admin_email>")
        sys.exit(1)

    email = sys.argv[1].strip()
    print(f"Looking up tenant for email: {email}")
    tenant_id = get_tenant_id(email)
    print(f"Found tenant_id: {tenant_id}")

    # Each entry: (title, author, isbn, publisher, year, genre, desc, price, stock, lang, shelf_name, shelf_number, keywords)
    books = [
        (
            "The Great Gatsby",
            "F. Scott Fitzgerald",
            "9780743273565",
            "Scribner",
            1925,
            "Fiction",
            "A novel about the American Dream.",
            12.99,
            15,
            "English",
            "Fiction",
            "A-01",
            ["classic", "american literature", "jazz age", "tragedy"],
        ),
        (
            "To Kill a Mockingbird",
            "Harper Lee",
            "9780061935466",
            "HarperCollins",
            1960,
            "Fiction",
            "A story of racial injustice.",
            14.99,
            20,
            "English",
            "Fiction",
            "A-02",
            ["classic", "american literature", "justice", "race"],
        ),
        (
            "1984",
            "George Orwell",
            "9780451524935",
            "Signet Classic",
            1949,
            "Dystopian",
            "A totalitarian future society.",
            10.99,
            25,
            "English",
            "Dystopian",
            "B-01",
            ["dystopia", "totalitarianism", "classic", "political"],
        ),
        (
            "Pride and Prejudice",
            "Jane Austen",
            "9780141439518",
            "Penguin Classics",
            1813,
            "Romance",
            "A romantic novel of manners.",
            9.99,
            18,
            "English",
            "Fiction",
            "A-03",
            ["classic", "romance", "british literature", "19th century"],
        ),
        (
            "The Catcher in the Rye",
            "J.D. Salinger",
            "9780316769174",
            "Little Brown",
            1951,
            "Fiction",
            "A story of teenage alienation.",
            11.99,
            12,
            "English",
            "Fiction",
            "A-04",
            ["coming of age", "american literature", "classic", "teen"],
        ),
        (
            "Brave New World",
            "Aldous Huxley",
            "9780060850524",
            "Harper Perennial",
            1932,
            "Dystopian",
            "A dystopian social science fiction.",
            12.99,
            10,
            "English",
            "Dystopian",
            "B-02",
            ["dystopia", "science fiction", "classic", "social commentary"],
        ),
        (
            "The Hobbit",
            "J.R.R. Tolkien",
            "9780547928227",
            "Houghton Mifflin",
            1937,
            "Fantasy",
            "A fantasy adventure story.",
            13.99,
            30,
            "English",
            "Sci-Fi & Fantasy",
            "C-01",
            ["fantasy", "adventure", "middle-earth", "classic"],
        ),
        (
            "Harry Potter and the Sorcerer's Stone",
            "J.K. Rowling",
            "9780590353427",
            "Scholastic",
            1997,
            "Fantasy",
            "A young wizard''s first year at Hogwarts.",
            14.99,
            50,
            "English",
            "Sci-Fi & Fantasy",
            "C-02",
            ["fantasy", "magic", "young adult", "wizards"],
        ),
        (
            "The Lord of the Rings",
            "J.R.R. Tolkien",
            "9780618640157",
            "Houghton Mifflin",
            1954,
            "Fantasy",
            "An epic high-fantasy novel.",
            24.99,
            20,
            "English",
            "Sci-Fi & Fantasy",
            "C-03",
            ["fantasy", "epic", "middle-earth", "adventure"],
        ),
        (
            "Animal Farm",
            "George Orwell",
            "9780451526342",
            "Signet Classic",
            1945,
            "Satire",
            "An allegorical novella.",
            8.99,
            22,
            "English",
            "Fiction",
            "A-05",
            ["satire", "allegory", "political", "classic"],
        ),
        (
            "The Alchemist",
            "Paulo Coelho",
            "9780062315007",
            "HarperOne",
            1988,
            "Fiction",
            "A philosophical novel.",
            13.99,
            35,
            "English",
            "Fiction",
            "A-06",
            ["philosophy", "spiritual", "adventure", "bestseller"],
        ),
        (
            "Fahrenheit 451",
            "Ray Bradbury",
            "9781451673319",
            "Simon Schuster",
            1953,
            "Dystopian",
            "A future where books are burned.",
            10.99,
            18,
            "English",
            "Dystopian",
            "B-03",
            ["dystopia", "censorship", "science fiction", "classic"],
        ),
        (
            "Don Quixote",
            "Miguel de Cervantes",
            "9780060934347",
            "HarperCollins",
            1605,
            "Classic",
            "Adventures of a wannabe knight.",
            15.99,
            8,
            "English",
            "Classics",
            "D-01",
            ["classic", "spanish literature", "satire", "adventure"],
        ),
        (
            "Moby Dick",
            "Herman Melville",
            "9781503280786",
            "CreateSpace",
            1851,
            "Adventure",
            "The quest to hunt a white whale.",
            9.99,
            10,
            "English",
            "Classics",
            "D-02",
            ["adventure", "sea", "classic", "american literature"],
        ),
        (
            "The Divine Comedy",
            "Dante Alighieri",
            "9780142437223",
            "Penguin Classics",
            1320,
            "Poetry",
            "A journey through the afterlife.",
            14.99,
            7,
            "English",
            "Poetry & Drama",
            "E-01",
            ["poetry", "classic", "italian literature", "medieval"],
        ),
        (
            "War and Peace",
            "Leo Tolstoy",
            "9781400079988",
            "Vintage",
            1869,
            "Historical Fiction",
            "A panoramic view of Russian life.",
            19.99,
            6,
            "English",
            "Historical",
            "F-01",
            ["historical fiction", "russian literature", "classic", "war"],
        ),
        (
            "Crime and Punishment",
            "Fyodor Dostoevsky",
            "9780143058144",
            "Penguin Classics",
            1866,
            "Psychological Fiction",
            "A psychological study of a murderer.",
            12.99,
            14,
            "English",
            "Classics",
            "D-03",
            ["psychology", "russian literature", "classic", "crime"],
        ),
        (
            "Hamlet",
            "William Shakespeare",
            "9780743477123",
            "Simon Schuster",
            1603,
            "Drama",
            "A tragedy of revenge.",
            8.99,
            20,
            "English",
            "Poetry & Drama",
            "E-02",
            ["drama", "shakespeare", "tragedy", "classic"],
        ),
        (
            "Wuthering Heights",
            "Emily Bronte",
            "9780141439556",
            "Penguin Classics",
            1847,
            "Gothic Fiction",
            "A dark romantic novel.",
            10.99,
            16,
            "English",
            "Gothic & Horror",
            "G-01",
            ["gothic", "romance", "classic", "british literature"],
        ),
        (
            "Jane Eyre",
            "Charlotte Bronte",
            "9780141441146",
            "Penguin Classics",
            1847,
            "Romance",
            "A young orphan''s journey.",
            11.99,
            19,
            "English",
            "Fiction",
            "A-07",
            ["romance", "classic", "british literature", "coming of age"],
        ),
        (
            "Great Expectations",
            "Charles Dickens",
            "9780141439563",
            "Penguin Classics",
            1861,
            "Fiction",
            "The story of orphan Pip.",
            10.99,
            13,
            "English",
            "Classics",
            "D-04",
            ["classic", "british literature", "coming of age", "victorian"],
        ),
        (
            "The Odyssey",
            "Homer",
            "9780140268867",
            "Penguin Classics",
            -800,
            "Epic Poetry",
            "Odysseus''s journey home from Troy.",
            12.99,
            9,
            "English",
            "Poetry & Drama",
            "E-03",
            ["epic", "greek literature", "ancient", "adventure"],
        ),
        (
            "The Iliad",
            "Homer",
            "9780140275360",
            "Penguin Classics",
            -750,
            "Epic Poetry",
            "The Trojan War epic.",
            12.99,
            8,
            "English",
            "Poetry & Drama",
            "E-04",
            ["epic", "greek literature", "ancient", "war"],
        ),
        (
            "Ulysses",
            "James Joyce",
            "9781840226355",
            "Wordsworth Editions",
            1922,
            "Modernist Fiction",
            "A day in Dublin''s life.",
            14.99,
            5,
            "English",
            "Classics",
            "D-05",
            ["modernism", "irish literature", "stream of consciousness", "classic"],
        ),
        (
            "A Tale of Two Cities",
            "Charles Dickens",
            "9780141439600",
            "Penguin Classics",
            1859,
            "Historical Fiction",
            "The French Revolution era.",
            10.99,
            15,
            "English",
            "Historical",
            "F-02",
            ["historical fiction", "french revolution", "classic", "dickens"],
        ),
        (
            "The Count of Monte Cristo",
            "Alexandre Dumas",
            "9780140449266",
            "Penguin Classics",
            1844,
            "Adventure",
            "A story of betrayal and revenge.",
            16.99,
            12,
            "English",
            "Historical",
            "F-03",
            ["adventure", "revenge", "classic", "french literature"],
        ),
        (
            "Les Miserables",
            "Victor Hugo",
            "9780451419439",
            "Signet Classic",
            1862,
            "Historical Fiction",
            "France in the 19th century.",
            18.99,
            10,
            "English",
            "Historical",
            "F-04",
            ["historical fiction", "french literature", "classic", "social justice"],
        ),
        (
            "Anna Karenina",
            "Leo Tolstoy",
            "9780143035008",
            "Penguin Classics",
            1878,
            "Romance",
            "A tragic love story.",
            15.99,
            11,
            "English",
            "Classics",
            "D-06",
            ["romance", "russian literature", "classic", "tragedy"],
        ),
        (
            "Madame Bovary",
            "Gustave Flaubert",
            "9780140449129",
            "Penguin Classics",
            1857,
            "Realist Fiction",
            "A provincial doctor''s wife.",
            11.99,
            9,
            "English",
            "Classics",
            "D-07",
            ["realism", "french literature", "classic", "tragedy"],
        ),
        (
            "The Brothers Karamazov",
            "Fyodor Dostoevsky",
            "9780374528379",
            "Farrar Straus",
            1880,
            "Philosophical Fiction",
            "A spiritual drama of moral debates.",
            17.99,
            8,
            "English",
            "Classics",
            "D-08",
            ["philosophy", "russian literature", "classic", "religion"],
        ),
        (
            "Invisible Man",
            "Ralph Ellison",
            "9780679732761",
            "Vintage",
            1952,
            "Fiction",
            "A Black man''s experience in America.",
            13.99,
            14,
            "English",
            "Fiction",
            "A-08",
            ["american literature", "race", "identity", "classic"],
        ),
        (
            "One Hundred Years of Solitude",
            "Gabriel Garcia Marquez",
            "9780060883287",
            "HarperCollins",
            1967,
            "Magical Realism",
            "The Buendia family''s story.",
            14.99,
            16,
            "English",
            "Fiction",
            "A-09",
            ["magical realism", "latin american literature", "classic", "family"],
        ),
        (
            "Love in the Time of Cholera",
            "Gabriel Garcia Marquez",
            "9780307389732",
            "Vintage",
            1985,
            "Romance",
            "A love story spanning fifty years.",
            14.99,
            12,
            "English",
            "Fiction",
            "A-10",
            ["romance", "magical realism", "latin american literature"],
        ),
        (
            "The Sun Also Rises",
            "Ernest Hemingway",
            "9780743297332",
            "Scribner",
            1926,
            "Fiction",
            "The Lost Generation in Europe.",
            12.99,
            10,
            "English",
            "Fiction",
            "A-11",
            ["american literature", "lost generation", "classic", "1920s"],
        ),
        (
            "A Farewell to Arms",
            "Ernest Hemingway",
            "9780684801469",
            "Scribner",
            1929,
            "War Fiction",
            "A wartime love story.",
            12.99,
            11,
            "English",
            "Historical",
            "F-05",
            ["war", "romance", "american literature", "wwi"],
        ),
        (
            "For Whom the Bell Tolls",
            "Ernest Hemingway",
            "9780684803357",
            "Scribner",
            1940,
            "War Fiction",
            "The Spanish Civil War.",
            13.99,
            9,
            "English",
            "Historical",
            "F-06",
            ["war", "spanish civil war", "american literature"],
        ),
        (
            "The Old Man and the Sea",
            "Ernest Hemingway",
            "9780684801223",
            "Scribner",
            1952,
            "Fiction",
            "An old fisherman''s epic struggle.",
            10.99,
            17,
            "English",
            "Fiction",
            "A-12",
            ["american literature", "sea", "perseverance", "classic"],
        ),
        (
            "Of Mice and Men",
            "John Steinbeck",
            "9780140177398",
            "Penguin Books",
            1937,
            "Fiction",
            "Two ranch workers'' friendship.",
            9.99,
            20,
            "English",
            "Fiction",
            "A-13",
            ["american literature", "friendship", "great depression", "classic"],
        ),
        (
            "The Grapes of Wrath",
            "John Steinbeck",
            "9780143039433",
            "Penguin Books",
            1939,
            "Fiction",
            "The Great Depression''s toll.",
            13.99,
            14,
            "English",
            "Historical",
            "F-07",
            ["american literature", "great depression", "social commentary", "classic"],
        ),
        (
            "East of Eden",
            "John Steinbeck",
            "9780142004235",
            "Penguin Books",
            1952,
            "Fiction",
            "Two families in Salinas Valley.",
            15.99,
            10,
            "English",
            "Fiction",
            "A-14",
            ["american literature", "family", "good vs evil", "steinbeck"],
        ),
        (
            "Catch-22",
            "Joseph Heller",
            "9781451626650",
            "Simon Schuster",
            1961,
            "Satire",
            "The absurdity of war.",
            13.99,
            15,
            "English",
            "Fiction",
            "A-15",
            ["satire", "war", "black comedy", "classic"],
        ),
        (
            "Slaughterhouse-Five",
            "Kurt Vonnegut",
            "9780440180296",
            "Dell",
            1969,
            "Science Fiction",
            "WWII and time travel.",
            11.99,
            18,
            "English",
            "Sci-Fi & Fantasy",
            "C-04",
            ["science fiction", "time travel", "wwii", "satire"],
        ),
        (
            "The Handmaid''s Tale",
            "Margaret Atwood",
            "9780385490818",
            "Anchor Books",
            1985,
            "Dystopian",
            "A theocratic future America.",
            13.99,
            22,
            "English",
            "Dystopian",
            "B-04",
            ["dystopia", "feminism", "speculative fiction", "canadian literature"],
        ),
        (
            "Beloved",
            "Toni Morrison",
            "9781400033416",
            "Vintage",
            1987,
            "Fiction",
            "A former slave''s haunting.",
            13.99,
            14,
            "English",
            "Fiction",
            "A-16",
            ["american literature", "slavery", "haunting", "pulitzer"],
        ),
        (
            "The Color Purple",
            "Alice Walker",
            "9780156028356",
            "Mariner Books",
            1982,
            "Fiction",
            "A Black woman in the South.",
            12.99,
            13,
            "English",
            "Fiction",
            "A-17",
            ["american literature", "race", "feminism", "pulitzer"],
        ),
        (
            "Their Eyes Were Watching God",
            "Zora Neale Hurston",
            "9780061859885",
            "Amistad",
            1937,
            "Fiction",
            "A Southern Black woman''s journey.",
            12.99,
            11,
            "English",
            "Fiction",
            "A-18",
            ["american literature", "harlem renaissance", "self-discovery"],
        ),
        (
            "Lolita",
            "Vladimir Nabokov",
            "9780679723165",
            "Vintage",
            1955,
            "Fiction",
            "A controversial novel.",
            12.99,
            8,
            "English",
            "Fiction",
            "A-19",
            ["controversial", "russian-american literature", "classic"],
        ),
        (
            "The Stranger",
            "Albert Camus",
            "9780679720201",
            "Vintage",
            1942,
            "Philosophical Fiction",
            "Existentialism in French Algeria.",
            10.99,
            19,
            "English",
            "Philosophy",
            "H-01",
            ["existentialism", "french literature", "philosophy", "classic"],
        ),
        (
            "Nausea",
            "Jean-Paul Sartre",
            "9780811201568",
            "New Directions",
            1938,
            "Philosophical Fiction",
            "Existentialism and consciousness.",
            11.99,
            9,
            "English",
            "Philosophy",
            "H-02",
            ["existentialism", "french literature", "philosophy"],
        ),
        (
            "In Search of Lost Time",
            "Marcel Proust",
            "9780141180441",
            "Penguin Classics",
            1913,
            "Modernist Fiction",
            "Memory and time in France.",
            29.99,
            4,
            "English",
            "Classics",
            "D-09",
            ["modernism", "french literature", "memory", "classic"],
        ),
        (
            "The Trial",
            "Franz Kafka",
            "9780805210408",
            "Schocken",
            1925,
            "Absurdist Fiction",
            "A man arrested without reason.",
            11.99,
            12,
            "English",
            "Fiction",
            "A-20",
            ["absurdism", "kafka", "german literature", "surreal"],
        ),
        (
            "The Metamorphosis",
            "Franz Kafka",
            "9780553213690",
            "Bantam Classics",
            1915,
            "Absurdist Fiction",
            "A man transformed into an insect.",
            8.99,
            20,
            "English",
            "Fiction",
            "A-21",
            ["absurdism", "kafka", "german literature", "surreal"],
        ),
        (
            "Siddhartha",
            "Hermann Hesse",
            "9780553208849",
            "Bantam Books",
            1922,
            "Philosophical Fiction",
            "A spiritual journey in ancient India.",
            10.99,
            25,
            "English",
            "Philosophy",
            "H-03",
            ["philosophy", "spirituality", "eastern philosophy", "self-discovery"],
        ),
        (
            "Steppenwolf",
            "Hermann Hesse",
            "9780312278670",
            "Picador",
            1927,
            "Philosophical Fiction",
            "A man between two worlds.",
            12.99,
            10,
            "English",
            "Philosophy",
            "H-04",
            ["philosophy", "identity", "german literature"],
        ),
        (
            "The Picture of Dorian Gray",
            "Oscar Wilde",
            "9780141439570",
            "Penguin Classics",
            1890,
            "Gothic Fiction",
            "A beautiful man''s dark bargain.",
            10.99,
            16,
            "English",
            "Gothic & Horror",
            "G-02",
            ["gothic", "british literature", "morality", "classic"],
        ),
        (
            "Frankenstein",
            "Mary Shelley",
            "9780141439471",
            "Penguin Classics",
            1818,
            "Gothic Fiction",
            "The dangers of playing God.",
            9.99,
            22,
            "English",
            "Gothic & Horror",
            "G-03",
            ["gothic", "horror", "science fiction", "classic"],
        ),
        (
            "Dracula",
            "Bram Stoker",
            "9780141439082",
            "Penguin Classics",
            1897,
            "Horror",
            "The famous vampire story.",
            10.99,
            20,
            "English",
            "Gothic & Horror",
            "G-04",
            ["horror", "gothic", "vampire", "classic"],
        ),
        (
            "Rebecca",
            "Daphne du Maurier",
            "9780380730407",
            "Avon",
            1938,
            "Gothic Mystery",
            "A new wife haunted by her predecessor.",
            12.99,
            15,
            "English",
            "Gothic & Horror",
            "G-05",
            ["gothic", "mystery", "suspense", "british literature"],
        ),
        (
            "Gone with the Wind",
            "Margaret Mitchell",
            "9781451635621",
            "Scribner",
            1936,
            "Historical Romance",
            "The American Civil War era.",
            16.99,
            18,
            "English",
            "Historical",
            "F-08",
            ["historical romance", "civil war", "american literature", "pulitzer"],
        ),
        (
            "Little Women",
            "Louisa May Alcott",
            "9780147514011",
            "Puffin Classics",
            1868,
            "Fiction",
            "Four sisters growing up.",
            10.99,
            24,
            "English",
            "Fiction",
            "A-22",
            ["coming of age", "family", "american literature", "classic"],
        ),
        (
            "Middlemarch",
            "George Eliot",
            "9780141439549",
            "Penguin Classics",
            1874,
            "Realist Fiction",
            "Provincial English life.",
            14.99,
            8,
            "English",
            "Classics",
            "D-10",
            ["realism", "british literature", "victorian", "classic"],
        ),
        (
            "Tess of the d''Urbervilles",
            "Thomas Hardy",
            "9780141439594",
            "Penguin Classics",
            1891,
            "Tragedy",
            "A young country woman''s fate.",
            11.99,
            10,
            "English",
            "Classics",
            "D-11",
            ["tragedy", "british literature", "victorian", "classic"],
        ),
        (
            "Jude the Obscure",
            "Thomas Hardy",
            "9780140435382",
            "Penguin Classics",
            1895,
            "Fiction",
            "A working-class man''s ambitions.",
            11.99,
            8,
            "English",
            "Classics",
            "D-12",
            ["british literature", "victorian", "social commentary"],
        ),
        (
            "The Adventures of Huckleberry Finn",
            "Mark Twain",
            "9780486280615",
            "Dover Publications",
            1884,
            "Adventure",
            "A boy''s journey down the Mississippi.",
            7.99,
            18,
            "English",
            "Fiction",
            "A-23",
            ["adventure", "american literature", "coming of age", "classic"],
        ),
        (
            "The Adventures of Tom Sawyer",
            "Mark Twain",
            "9780143039563",
            "Penguin Classics",
            1876,
            "Adventure",
            "A boy''s adventures in Missouri.",
            8.99,
            20,
            "English",
            "Fiction",
            "A-24",
            ["adventure", "american literature", "childhood", "classic"],
        ),
        (
            "Leaves of Grass",
            "Walt Whitman",
            "9780140421996",
            "Penguin Classics",
            1855,
            "Poetry",
            "Influential American poetry.",
            12.99,
            10,
            "English",
            "Poetry & Drama",
            "E-05",
            ["poetry", "american literature", "nature", "classic"],
        ),
        (
            "The Waste Land",
            "T.S. Eliot",
            "9780156948777",
            "Mariner Books",
            1922,
            "Poetry",
            "A landmark modernist poem.",
            11.99,
            8,
            "English",
            "Poetry & Drama",
            "E-06",
            ["poetry", "modernism", "british literature", "classic"],
        ),
        (
            "Beloved Infidel",
            "Sheilah Graham",
            "9780553271638",
            "Bantam Books",
            1958,
            "Memoir",
            "A Hollywood romance memoir.",
            9.99,
            5,
            "English",
            "Non-Fiction",
            "I-01",
            ["memoir", "biography", "hollywood", "romance"],
        ),
        (
            "A Room with a View",
            "E.M. Forster",
            "9780141441825",
            "Penguin Classics",
            1908,
            "Romance",
            "An Edwardian love story.",
            10.99,
            14,
            "English",
            "Fiction",
            "A-25",
            ["romance", "british literature", "edwardian", "classic"],
        ),
        (
            "Howards End",
            "E.M. Forster",
            "9780141441146",
            "Penguin Classics",
            1910,
            "Fiction",
            "Class conflict in England.",
            11.99,
            9,
            "English",
            "Fiction",
            "A-26",
            ["british literature", "class", "edwardian", "social commentary"],
        ),
        (
            "Mrs Dalloway",
            "Virginia Woolf",
            "9780156628709",
            "Mariner Books",
            1925,
            "Modernist Fiction",
            "A day in London.",
            10.99,
            11,
            "English",
            "Classics",
            "D-13",
            ["modernism", "stream of consciousness", "british literature", "classic"],
        ),
        (
            "To the Lighthouse",
            "Virginia Woolf",
            "9780156907392",
            "Mariner Books",
            1927,
            "Modernist Fiction",
            "A family''s holiday in Scotland.",
            10.99,
            10,
            "English",
            "Classics",
            "D-14",
            ["modernism", "stream of consciousness", "british literature"],
        ),
        (
            "Orlando",
            "Virginia Woolf",
            "9780156701600",
            "Mariner Books",
            1928,
            "Fiction",
            "A gender-bending fantasia.",
            11.99,
            8,
            "English",
            "Fiction",
            "A-27",
            ["modernism", "gender", "british literature", "fantasy"],
        ),
        (
            "The Sound and the Fury",
            "William Faulkner",
            "9780679732242",
            "Vintage",
            1929,
            "Modernist Fiction",
            "The Compson family''s decline.",
            12.99,
            7,
            "English",
            "Fiction",
            "A-28",
            ["modernism", "american literature", "southern gothic", "classic"],
        ),
        (
            "As I Lay Dying",
            "William Faulkner",
            "9780679724258",
            "Vintage",
            1930,
            "Fiction",
            "A poor family''s journey.",
            11.99,
            9,
            "English",
            "Fiction",
            "A-29",
            ["american literature", "southern gothic", "stream of consciousness"],
        ),
        (
            "Light in August",
            "William Faulkner",
            "9780679732266",
            "Vintage",
            1932,
            "Fiction",
            "Race and identity in the South.",
            12.99,
            8,
            "English",
            "Fiction",
            "A-30",
            ["american literature", "southern gothic", "race", "identity"],
        ),
        (
            "The Bell Jar",
            "Sylvia Plath",
            "9780060837020",
            "HarperCollins",
            1963,
            "Fiction",
            "A young woman''s breakdown.",
            12.99,
            20,
            "English",
            "Fiction",
            "A-31",
            ["mental health", "feminism", "american literature", "coming of age"],
        ),
        (
            "On the Road",
            "Jack Kerouac",
            "9780140283297",
            "Penguin Books",
            1957,
            "Fiction",
            "The Beat Generation''s travels.",
            12.99,
            15,
            "English",
            "Fiction",
            "A-32",
            ["beat generation", "american literature", "road trip", "countercultural"],
        ),
        (
            "Naked Lunch",
            "William S. Burroughs",
            "9780802140180",
            "Grove Press",
            1959,
            "Experimental Fiction",
            "A surreal drug-fueled journey.",
            13.99,
            6,
            "English",
            "Fiction",
            "A-33",
            ["experimental", "beat generation", "surreal", "controversial"],
        ),
        (
            "The Electric Kool-Aid Acid Test",
            "Tom Wolfe",
            "9780553380644",
            "Bantam",
            1968,
            "Non-Fiction",
            "Ken Kesey and the Merry Pranksters.",
            12.99,
            7,
            "English",
            "Non-Fiction",
            "I-02",
            ["non-fiction", "counterculture", "1960s", "gonzo"],
        ),
        (
            "Fear and Loathing in Las Vegas",
            "Hunter S. Thompson",
            "9780679785897",
            "Vintage",
            1971,
            "Gonzo Journalism",
            "A wild trip to Las Vegas.",
            13.99,
            12,
            "English",
            "Non-Fiction",
            "I-03",
            [
                "gonzo journalism",
                "counterculture",
                "american literature",
                "drug culture",
            ],
        ),
        (
            "Zen and the Art of Motorcycle Maintenance",
            "Robert M. Pirsig",
            "9780060839871",
            "HarperTorch",
            1974,
            "Philosophy",
            "A philosophical road trip.",
            13.99,
            14,
            "English",
            "Philosophy",
            "H-05",
            ["philosophy", "road trip", "quality", "self-discovery"],
        ),
        (
            "The Road",
            "Cormac McCarthy",
            "9780307387899",
            "Vintage",
            2006,
            "Post-Apocalyptic",
            "A father and son''s survival.",
            13.99,
            20,
            "English",
            "Dystopian",
            "B-05",
            ["post-apocalyptic", "survival", "father-son", "pulitzer"],
        ),
        (
            "Blood Meridian",
            "Cormac McCarthy",
            "9780679728757",
            "Vintage",
            1985,
            "Western",
            "Violence on the US-Mexico border.",
            14.99,
            10,
            "English",
            "Fiction",
            "A-34",
            ["western", "violence", "american literature", "dark"],
        ),
        (
            "No Country for Old Men",
            "Cormac McCarthy",
            "9780307387134",
            "Vintage",
            2005,
            "Thriller",
            "A deadly game of cat and mouse.",
            13.99,
            15,
            "English",
            "Fiction",
            "A-35",
            ["thriller", "crime", "western", "american literature"],
        ),
        (
            "Song of Solomon",
            "Toni Morrison",
            "9781400033423",
            "Vintage",
            1977,
            "Fiction",
            "A Black family across generations.",
            13.99,
            10,
            "English",
            "Fiction",
            "A-36",
            ["american literature", "race", "family", "national book award"],
        ),
        (
            "The House on Mango Street",
            "Sandra Cisneros",
            "9780679734772",
            "Vintage",
            1984,
            "Fiction",
            "Growing up Latina in Chicago.",
            11.99,
            18,
            "English",
            "Fiction",
            "A-37",
            ["coming of age", "latina literature", "chicago", "identity"],
        ),
        (
            "Interpreter of Maladies",
            "Jhumpa Lahiri",
            "9780395927205",
            "Houghton Mifflin",
            1999,
            "Short Stories",
            "Indian-American immigrant life.",
            12.99,
            16,
            "English",
            "Fiction",
            "A-38",
            ["short stories", "indian american", "immigration", "pulitzer"],
        ),
        (
            "The Namesake",
            "Jhumpa Lahiri",
            "9780618485222",
            "Houghton Mifflin",
            2003,
            "Fiction",
            "An immigrant family in America.",
            13.99,
            15,
            "English",
            "Fiction",
            "A-39",
            ["immigration", "indian american", "identity", "family"],
        ),
        (
            "White Teeth",
            "Zadie Smith",
            "9780375703867",
            "Vintage",
            2000,
            "Fiction",
            "Multicultural London.",
            14.99,
            13,
            "English",
            "Fiction",
            "A-40",
            ["multicultural", "british literature", "identity", "contemporary"],
        ),
        (
            "Atonement",
            "Ian McEwan",
            "9780385721707",
            "Anchor Books",
            2001,
            "Fiction",
            "A lie that destroys lives.",
            13.99,
            14,
            "English",
            "Fiction",
            "A-41",
            ["british literature", "guilt", "war", "contemporary"],
        ),
        (
            "Never Let Me Go",
            "Kazuo Ishiguro",
            "9781400078776",
            "Vintage",
            2005,
            "Dystopian",
            "Clones coming of age.",
            13.99,
            18,
            "English",
            "Dystopian",
            "B-06",
            ["dystopia", "science fiction", "british literature", "coming of age"],
        ),
        (
            "The Remains of the Day",
            "Kazuo Ishiguro",
            "9780679731726",
            "Vintage",
            1989,
            "Fiction",
            "An English butler reflects.",
            12.99,
            12,
            "English",
            "Fiction",
            "A-42",
            ["british literature", "memory", "regret", "booker prize"],
        ),
        (
            "Midnight''s Children",
            "Salman Rushdie",
            "9780812976533",
            "Random House",
            1981,
            "Magical Realism",
            "India''s independence story.",
            15.99,
            9,
            "English",
            "Fiction",
            "A-43",
            ["magical realism", "india", "independence", "booker prize"],
        ),
        (
            "The Satanic Verses",
            "Salman Rushdie",
            "9780812976526",
            "Random House",
            1988,
            "Magical Realism",
            "A controversial novel.",
            15.99,
            6,
            "English",
            "Fiction",
            "A-44",
            ["magical realism", "controversial", "identity", "religion"],
        ),
        (
            "Things Fall Apart",
            "Chinua Achebe",
            "9780385474542",
            "Anchor Books",
            1958,
            "Fiction",
            "Colonial Africa''s impact.",
            11.99,
            20,
            "English",
            "Fiction",
            "A-45",
            ["african literature", "colonialism", "nigeria", "classic"],
        ),
        (
            "Arrow of God",
            "Chinua Achebe",
            "9780385014717",
            "Anchor Books",
            1964,
            "Fiction",
            "Colonial Nigeria.",
            11.99,
            10,
            "English",
            "Fiction",
            "A-46",
            ["african literature", "colonialism", "nigeria"],
        ),
        (
            "Season of Migration to the North",
            "Tayeb Salih",
            "9780894775697",
            "Heinemann",
            1966,
            "Fiction",
            "Sudan meets Europe.",
            12.99,
            7,
            "English",
            "Fiction",
            "A-47",
            ["african literature", "postcolonialism", "identity", "arabic literature"],
        ),
        (
            "The God of Small Things",
            "Arundhati Roy",
            "9780812979657",
            "Random House",
            1997,
            "Fiction",
            "India''s caste system.",
            13.99,
            16,
            "English",
            "Fiction",
            "A-48",
            ["indian literature", "caste", "love", "booker prize"],
        ),
        (
            "Life of Pi",
            "Yann Martel",
            "9780156027328",
            "Mariner Books",
            2001,
            "Fiction",
            "A boy and a tiger at sea.",
            13.99,
            25,
            "English",
            "Fiction",
            "A-49",
            ["adventure", "survival", "spirituality", "booker prize"],
        ),
        (
            "The Kite Runner",
            "Khaled Hosseini",
            "9781594631931",
            "Riverhead Books",
            2003,
            "Fiction",
            "Afghanistan and redemption.",
            14.99,
            30,
            "English",
            "Fiction",
            "A-50",
            ["afghanistan", "redemption", "friendship", "bestseller"],
        ),
        (
            "A Thousand Splendid Suns",
            "Khaled Hosseini",
            "9781594483073",
            "Riverhead Books",
            2007,
            "Fiction",
            "Two Afghan women''s bond.",
            14.99,
            25,
            "English",
            "Fiction",
            "A-51",
            ["afghanistan", "women", "friendship", "war"],
        ),
        # ── Non-Fiction ──────────────────────────────────────────────────────────
        (
            "Sapiens: A Brief History of Humankind",
            "Yuval Noah Harari",
            "9780062316097",
            "Harper",
            2011,
            "History",
            "How Homo sapiens conquered the world.",
            16.99,
            40,
            "English",
            "Non-Fiction",
            "I-04",
            ["history", "anthropology", "evolution", "bestseller"],
        ),
        (
            "Homo Deus: A Brief History of Tomorrow",
            "Yuval Noah Harari",
            "9780062464316",
            "Harper",
            2015,
            "History",
            "What will become of humanity in the future?",
            16.99,
            25,
            "English",
            "Non-Fiction",
            "I-05",
            ["history", "future", "technology", "philosophy"],
        ),
        (
            "A Short History of Nearly Everything",
            "Bill Bryson",
            "9780767908184",
            "Broadway Books",
            2003,
            "Science",
            "A popular science tour of the universe.",
            15.99,
            22,
            "English",
            "Non-Fiction",
            "I-06",
            ["science", "popular science", "universe", "nature"],
        ),
        (
            "The Selfish Gene",
            "Richard Dawkins",
            "9780198788607",
            "Oxford University Press",
            1976,
            "Science",
            "Genes as the unit of natural selection.",
            14.99,
            18,
            "English",
            "Non-Fiction",
            "I-07",
            ["biology", "evolution", "genetics", "popular science"],
        ),
        (
            "A Brief History of Time",
            "Stephen Hawking",
            "9780553380163",
            "Bantam Books",
            1988,
            "Science",
            "From the Big Bang to black holes.",
            13.99,
            30,
            "English",
            "Non-Fiction",
            "I-08",
            ["physics", "cosmology", "black holes", "popular science"],
        ),
        (
            "The Double Helix",
            "James D. Watson",
            "9780743216302",
            "Scribner",
            1968,
            "Science",
            "Personal account of the discovery of DNA.",
            12.99,
            15,
            "English",
            "Non-Fiction",
            "I-09",
            ["biology", "dna", "science history", "memoir"],
        ),
        (
            "Silent Spring",
            "Rachel Carson",
            "9780618253050",
            "Houghton Mifflin",
            1962,
            "Environment",
            "The environmental impact of pesticides.",
            13.99,
            20,
            "English",
            "Non-Fiction",
            "I-10",
            ["environment", "ecology", "pesticides", "nature"],
        ),
        (
            "The Sixth Extinction",
            "Elizabeth Kolbert",
            "9780805092998",
            "Henry Holt",
            2014,
            "Environment",
            "An unnatural history of mass extinction.",
            15.99,
            18,
            "English",
            "Non-Fiction",
            "I-11",
            ["environment", "extinction", "climate change", "pulitzer"],
        ),
        (
            "Thinking, Fast and Slow",
            "Daniel Kahneman",
            "9780374533557",
            "Farrar Straus",
            2011,
            "Psychology",
            "Two systems that drive the way we think.",
            16.99,
            35,
            "English",
            "Non-Fiction",
            "I-12",
            ["psychology", "behavioral economics", "decision making", "bestseller"],
        ),
        (
            "The Power of Habit",
            "Charles Duhigg",
            "9781400069286",
            "Random House",
            2012,
            "Psychology",
            "Why we do what we do in life and business.",
            14.99,
            28,
            "English",
            "Non-Fiction",
            "I-13",
            ["psychology", "habits", "neuroscience", "self-help"],
        ),
        (
            "Man''s Search for Meaning",
            "Viktor E. Frankl",
            "9780807014295",
            "Beacon Press",
            1946,
            "Psychology",
            "Finding purpose in life even in suffering.",
            12.99,
            40,
            "English",
            "Non-Fiction",
            "I-14",
            ["psychology", "holocaust", "philosophy", "meaning"],
        ),
        (
            "Educated",
            "Tara Westover",
            "9780399590504",
            "Random House",
            2018,
            "Memoir",
            "A memoir about education and self-invention.",
            16.99,
            35,
            "English",
            "Non-Fiction",
            "I-15",
            ["memoir", "education", "family", "bestseller"],
        ),
        (
            "The Glass Castle",
            "Jeannette Walls",
            "9780743247542",
            "Scribner",
            2005,
            "Memoir",
            "A family''s unconventional nomadic childhood.",
            14.99,
            25,
            "English",
            "Non-Fiction",
            "I-16",
            ["memoir", "family", "poverty", "resilience"],
        ),
        (
            "When Breath Becomes Air",
            "Paul Kalanithi",
            "9780812988406",
            "Random House",
            2016,
            "Memoir",
            "A neurosurgeon faces terminal cancer.",
            14.99,
            30,
            "English",
            "Non-Fiction",
            "I-17",
            ["memoir", "medicine", "mortality", "inspiring"],
        ),
        (
            "The Immortal Life of Henrietta Lacks",
            "Rebecca Skloot",
            "9781400052189",
            "Crown",
            2010,
            "Science",
            "How one woman''s cells changed medicine.",
            15.99,
            22,
            "English",
            "Non-Fiction",
            "I-18",
            ["science", "medicine", "race", "bioethics"],
        ),
        (
            "Into the Wild",
            "Jon Krakauer",
            "9780385486804",
            "Anchor Books",
            1996,
            "Adventure",
            "A young man abandons society for the Alaskan wilderness.",
            13.99,
            20,
            "English",
            "Non-Fiction",
            "I-19",
            ["adventure", "wilderness", "survival", "true story"],
        ),
        (
            "Into Thin Air",
            "Jon Krakauer",
            "9780385494786",
            "Anchor Books",
            1997,
            "Adventure",
            "A personal account of the 1996 Everest disaster.",
            14.99,
            18,
            "English",
            "Non-Fiction",
            "I-20",
            ["adventure", "mountaineering", "survival", "tragedy"],
        ),
        (
            "The Art of War",
            "Sun Tzu",
            "9780195014761",
            "Oxford University Press",
            -500,
            "Strategy",
            "Ancient Chinese military strategy treatise.",
            9.99,
            30,
            "English",
            "Non-Fiction",
            "I-21",
            ["strategy", "military", "leadership", "ancient"],
        ),
        (
            "How to Win Friends and Influence People",
            "Dale Carnegie",
            "9780671027032",
            "Simon Schuster",
            1936,
            "Self-Help",
            "Timeless advice on human relations.",
            12.99,
            45,
            "English",
            "Non-Fiction",
            "I-22",
            ["self-help", "communication", "business", "classic"],
        ),
        (
            "The 7 Habits of Highly Effective People",
            "Stephen R. Covey",
            "9781982137274",
            "Simon Schuster",
            1989,
            "Self-Help",
            "Principles for personal and professional effectiveness.",
            14.99,
            40,
            "English",
            "Non-Fiction",
            "I-23",
            ["self-help", "productivity", "leadership", "business"],
        ),
        (
            "Guns, Germs, and Steel",
            "Jared Diamond",
            "9780393317558",
            "W. W. Norton",
            1997,
            "History",
            "Why some societies conquered others.",
            16.99,
            25,
            "English",
            "Non-Fiction",
            "I-24",
            ["history", "anthropology", "geography", "pulitzer"],
        ),
        (
            "The Origin of Species",
            "Charles Darwin",
            "9780140432053",
            "Penguin Classics",
            1859,
            "Science",
            "On evolution by natural selection.",
            12.99,
            15,
            "English",
            "Non-Fiction",
            "I-25",
            ["biology", "evolution", "natural selection", "classic science"],
        ),
        (
            "Freakonomics",
            "Steven D. Levitt",
            "9780060731335",
            "William Morrow",
            2005,
            "Economics",
            "A rogue economist explores the hidden side of everything.",
            13.99,
            30,
            "English",
            "Non-Fiction",
            "I-26",
            ["economics", "behavioral economics", "statistics", "bestseller"],
        ),
        (
            "The Tipping Point",
            "Malcolm Gladwell",
            "9780316346627",
            "Little Brown",
            2000,
            "Sociology",
            "How little things can make a big difference.",
            14.99,
            28,
            "English",
            "Non-Fiction",
            "I-27",
            ["sociology", "psychology", "trends", "bestseller"],
        ),
        (
            "Outliers",
            "Malcolm Gladwell",
            "9780316017923",
            "Little Brown",
            2008,
            "Sociology",
            "The story of success.",
            14.99,
            32,
            "English",
            "Non-Fiction",
            "I-28",
            ["sociology", "success", "psychology", "bestseller"],
        ),
        (
            "The Body: A Guide for Occupants",
            "Bill Bryson",
            "9780385539302",
            "Doubleday",
            2019,
            "Science",
            "A tour of the human body.",
            16.99,
            20,
            "English",
            "Non-Fiction",
            "I-29",
            ["medicine", "biology", "anatomy", "popular science"],
        ),
        (
            "Bad Science",
            "Ben Goldacre",
            "9780865479180",
            "Faber and Faber",
            2008,
            "Science",
            "How journalists and quacks distort science.",
            13.99,
            16,
            "English",
            "Non-Fiction",
            "I-30",
            ["science", "medicine", "critical thinking", "journalism"],
        ),
    ]

    # Build INSERT SQL with shelf_name, shelf_number, keywords
    inserts = []
    for book in books:
        (
            title,
            author,
            isbn,
            publisher,
            year,
            genre,
            desc,
            price,
            stock,
            lang,
            shelf_name,
            shelf_number,
            keywords,
        ) = book

        # Escape single quotes in all string fields
        def esc(s: str) -> str:
            return s.replace("'", "''")

        kw_array = "ARRAY[" + ",".join(f"'{esc(k)}'" for k in keywords) + "]::text[]"
        inserts.append(
            f"(gen_random_uuid(), '{tenant_id}', '{esc(title)}', '{esc(author)}', '{esc(isbn)}', "
            f"'{esc(publisher)}', {year}, '{esc(genre)}', '{esc(desc)}', {price}, {stock}, '{esc(lang)}', "
            f"'{esc(shelf_name)}', '{esc(shelf_number)}', {kw_array})"
        )

    sql = (
        "INSERT INTO books (id, tenant_id, title, author, isbn, publisher, publish_year, "
        "genre, description, price, stock, language, shelf_name, shelf_number, keywords) VALUES\n"
        + ",\n".join(inserts)
        + " "
        "ON CONFLICT DO NOTHING;"
    )

    # Write SQL to temp file for debugging
    with open("/tmp/seed_books.sql", "w") as f:
        f.write(sql)

    print(f"Generated SQL with {len(inserts)} books. Executing...")

    result = subprocess.run(
        [
            "docker",
            "compose",
            "exec",
            "-T",
            "-e",
            "PGPASSWORD=changeme_strong_password_here",
            "postgres",
            "psql",
            "-U",
            "bookstore",
            "-d",
            "bookstore",
            "-c",
            sql,
        ],
        capture_output=True,
        text=True,
        cwd="/root/docs/projects/book-store-app/app",
    )

    if result.returncode == 0:
        print(f"Done! Output: {result.stdout.strip()}")
    else:
        print(f"ERROR: {result.stderr.strip()}")
        sys.exit(1)


if __name__ == "__main__":
    main()
